### ISSUE TITLE
NFC IOS Reader not working properly - nfcResult property isn't being returned

### ISSUE THREAD

**Issue by rodrigowpl** [Anyline/anyline-ocr-react-native-module#87] opened 2020-05-14 18:45 UTC
**Anyline React-Native Plugin version:** 

**I'm submitting a ...**  
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**  
[ ] Android
[x] iOS

**Current behavior:**

NFC reader seems don't work (or I'm not doing it right), `nfcResult` isn't being returned like [doc says](https://documentation.anyline.com/toc/platforms/react-native/advanced.html?highlight=nfc)

**Expected behavior:**
NFC reader works properly and `nfcResult` property be returned

**Steps to reproduce:**
Just set up as React Native getting started says and enable NFC plugin following [here](https://documentation.anyline.com/toc/platforms/react-native/advanced.html?highlight=nfc)

**Related code:**

Calling Anyline
```
  const values = await AnylineOCR.setupPromise(JSON.stringify(MRZConfig), 'scan');
  console.log(values)
```

MRZConfig
```
{
  license: environment.ANYLINE_LICENCE_KEY,
  options: {
    doneButton: {
      // iOS only. Android uses hardware back button.
      title: 'Manual Entry',
      type: 'rect', // fullwidth, rect
      cornerRadius: 0,
      // "backgroundColor":"#EEEEEE", // default clearcolor
      textColor: 'FFFFFF',
      textColorHighlighted: 'CCCCCC',
      fontSize: 33,
      fontName: 'HelveticaNeue',
      positionXAlignment: 'center', // left,right,center - no affect on fullwidth
      positionYAlignment: 'bottom', // top, center, bottom
      offset: {
        x: 0, // postive -> right
        y: -88, // postive -> down
      },
    },
    camera: {
      captureResolution: '1080p',
      ratioFromSize: {
        width: 125,
        height: 85,
      },
    },
    flash: {
      mode: 'manual',
      alignment: 'bottom_left',
    },
    viewPlugin: {
      plugin: {
        id: 'ID_NFC',
        nfcPlugin: {
          mrzConfig: {
            strictMode: false,
            cropAndTransformID: false,
          },
        },
        idPlugin: {
          mrzConfig: {
            strictMode: false,
            cropAndTransformID: false,
          },
        },
      },
      cutoutConfig: {
        style: 'rect',
        maxWidthPercent: '90%',
        maxHeightPercent: '90%',
        alignment: 'center',
        ratioFromSize: {
          width: 125,
          height: 85,
        },
        strokeWidth: 2,
        cornerRadius: 4,
        strokeColor: 'FFFFFF',
        outerColor: '000000',
        outerAlpha: 0.3,
        cropPadding: {
          x: 0,
          y: 0,
        },
        cropOffset: {
          x: 0,
          y: 0,
        },
        feedbackStrokeColor: '0099FF',
        offset: {
          x: 0,
          y: 30,
        },
      },
      scanFeedback: {
        style: 'rect',
        strokeColor: '0099FF',
        strokeWidth: 2,
        blinkOnResult: true,
        beepOnResult: true,
        vibrateOnResult: true,
      },
      cancelOnResult: true,
    },
    cropAndTransformErrorMessage: 'Edges are not detected',
  },
};
```

**Extra question**

If I'm doing config right, how should I test that? using the camera? proximity when camera open? Do you guys have an example?

Thanks

**Comment by philippAnyline** [comment] 2020-05-15 09:51
Hi rodrigowpl,

The Config looks alright, but there might be something wrong in the iOS eco-system/config, so I would need some additional information:

Which iPhone are you using? NFC for ID-NFC chips is only possible with an **iPhone 7 or later**.

Did you add the additional parameters to your Xcode project?
> Besides the scanPlugin config, you also have to add the following items to your apps project (info.plist and your Entitlements.plist file). This is necessary to tell the project, that is is allowed to use the NFC-Tag-Reader fucntionallity of iOS.
> 
> KEY: “NFCReaderUsageDescription” VALUE: <string>Please allow NFC access to read passports</string>
> KEY: “com.apple.developer.nfc.readersession.iso7816.select-identifiers” VALUE: <array> <string>A0000002471001</string> </array>
> KEY: “com.apple.developer.nfc.readersession.formats” VALUE: <array> <string>NDEF</string> <string>TAG</string> </array>


If yes: What happens when the Anyline scanView opens? Do you get the MRZ result and then the iOS dialog that you should move your phone towards the NFC chip? 

Hope I could help and I'm happy to answer additional questions :)

Best wishes,
Philipp

**Comment by rodrigowpl** [comment] 2020-05-15 13:28
Hi @philippAnyline 

Thanks for your answer,

Regarding your questions:

1: I've tried using iPhone XR and 7 plus

2: Yes I did, here are some print screens:
Info plis:
![image](https://user-images.githubusercontent.com/18172307/82055135-75923b80-9696-11ea-8e13-73732d98c1aa.png)

3: What happens is scanView open, scan the passport,  scan closes I get the result and nothing else happens, the dialog like you've said isn't showed

**Comment by JonasLaux** [comment] 2020-05-15 14:05
What happens if you comment out in the config your "idPlugin" and only use the nfcPlugin like [here](https://github.com/Anyline/anyline-ocr-react-native-module/blob/master/example/RNExampleApp/config/NFCAndMRZConfig.js#L28)?

**Comment by rodrigowpl** [comment] 2020-05-15 15:20
@JonasLaux If I do this I get an error when scan starts
![image](https://user-images.githubusercontent.com/18172307/82066953-759a3780-96a6-11ea-9269-bd3a75019b70.png)

**Comment by rodrigowpl** [comment] 2020-05-15 15:31
also I've tried copy and paste the exact same config file, got the same error above

**Comment by rodrigowpl** [comment] 2020-05-15 16:23
Update: I've also tried your [RNExampleApp](https://github.com/Anyline/anyline-ocr-react-native-module/tree/master/example/RNExampleApp) and it seems also don't work, getting this error:
![image](https://user-images.githubusercontent.com/18172307/82073123-2d334780-96af-11ea-9a8c-e901495a2bea.png)


Tried on iPhone XR and 7 Plus, it weird right? It should support

**Comment by philippAnyline** [comment] 2020-05-27 13:51
Hi rodrigowpl, Thanks for reporting this issue, we will look into it ASAP. We also have a release planned, which should be available on Monday. 

The error, that your device is not supporting NFC should only popup when either don't have all necessary options in your project or if your phone is not supporting it.

**Comment by onthebreeze** [comment] 2020-05-27 21:54
Should definitely work on iPhone XR - it surely has nfc

**Comment by rodrigowpl** [comment] 2020-05-27 21:56
@philippAnyline 
As I've said above, I've tried your internal example and following the docs in iPhone XR, that should definitely support

**Comment by onthebreeze** [comment] 2020-05-27 22:26
@philippAnyline - at present none of our four developers seem to be able to get this working.  I'm keen to know whether it's something we are doing wrong or whether there is a bug in your product.  Because if it's something we are doing wrong then we need to fid it anf fix it and we will invest effort into that between now and monday.  However it is a known bug in your product then we will know not to waste effort and instead just wait for your monday release.

Please let us know

**Comment by philippAnyline** [comment] 2020-05-28 08:27
Hi @onthebreeze, it seems like the issue is on our side. I will hopefully have a fix or update on monday.

**Comment by philippAnyline** [comment] 2020-05-28 09:55
Hi @onthebreeze @rodrigowpl, short update: 

Can you please make sure that you manually add the "Near Field Capability" within the Xcode project?

![image](https://user-images.githubusercontent.com/24568164/83127051-f7905480-a0d9-11ea-9364-795a2c4dee4f.png)

If I remember correctly, we cannot push this capability at the moment for our Example app, but we will try to find a solution to fix that issue.

**Comment by rodrigowpl** [comment] 2020-05-28 18:53
@philippAnyline yes I have this enabled
![image](https://user-images.githubusercontent.com/18172307/83181487-5619fa80-a0fb-11ea-8434-4b4fafd1a6a7.png)

**Comment by onthebreeze** [comment] 2020-06-02 06:57
so - did you release an update with a fix for this?

**Comment by AmirAtAnyline** [comment] 2020-06-03 14:33
Hi @onthebreeze @rodrigowpl

As well as adding NFC capability to the example app, an app identifier is needed from the Apple Developer portal. This is specific to the developer, so it won't work for anyone else.

Lastly, please check the two highlighted entries in Info.plist:

<img width="783" alt="info-plist" src="https://user-images.githubusercontent.com/53007639/83649687-c3c09d80-a5b7-11ea-9b28-7b6c29f9eae0.png">

Hopefully this will fix the issue for you.

Amir

**Comment by rodrigowpl** [comment] 2020-06-04 01:51
Hi @AmirAtAnyline I already have this configured since the begging. Thanks for you help anyway.

@philippAnyline said we would have a new version right? it would be 21? just saw the release notes

**Comment by rodrigowpl** [comment] 2020-06-04 15:42
@philippAnyline @AmirAtAnyline just updated to Anyline 21 and it seems worked now, the modal asking to move my phone towards to passport appear correctly, 

but now I'm getting this error
![image](https://user-images.githubusercontent.com/18172307/83778188-bb706d00-a660-11ea-8c7c-b50b6a82fe9a.png)

Does it seem an authentication error with my passport?

**Comment by philippAnyline** [comment] 2020-06-04 15:50
Hi @rodrigowpl, sorry for the late answer, release week in covid19 times was a bit different.
Which kind of passport (country) are you trying to read? Do you have the chance to try it on a different passport? And lastly, could you try to read the NFC chip on different positions & sides of the passport, since the data transfer might disconnect sometimes.  

We authenticate only in one way at the moment, and we might have some limitations if the passport is not conforming to that handshake.

It is also very important that your info.plist contains the two values that @AmirAtAnyline posted above. If the ISO78166 field is missing, it might trigger this issue as well.

Please give as as many details as possibe,

**Comment by rodrigowpl** [comment] 2020-06-04 15:59
@philippAnyline 

- It's a Brazillian passport, see this pic below:
![image](https://user-images.githubusercontent.com/18172307/83779881-dfcd4900-a662-11ea-8325-b791cc0ed91c.png)

Do you have some limitations depending on region or type? If so how could we know that? For transparency with our clients and handle to show a proper error, just show a generic one isn't so cool right?! :)

Also:
- I've tried several different positions, I still re-trying sometimes so I will keep you posted
- My configuration is exactly @AmirAtAnyline said

Thanks

**Comment by philippAnyline** [comment] 2020-06-04 17:16
@rodrigowpl Could you download our OCR Scanner app for iOS and try if it recognizes your passport(s)? This will help us to pin point the issue. 

Link to the app: https://apps.apple.com/at/app/anyline-ocr-scanner/id1121273374

Thanks and best wishes,
Philipp

**Comment by rodrigowpl** [comment] 2020-06-04 19:08
thanks, @philippAnyline just tried here, the same thing, unfortunately, maybe some issue with my passport?

It would be great if we could see more accurately log, is that possible?

**Comment by onthebreeze** [comment] 2020-06-04 21:17
I have also tested the iOS app with my uk passport. It does not work. It reads the mrz ok and then asks me to hold the phone over the chip.  I place the phone on the chip page and nothing happens. It says “reading” for a while - and then times our after about 30 seconds with no weir message

**Comment by onthebreeze** [comment] 2020-06-04 21:35
I tried a passport read of my UK using a competitor library - ReadID. It worked!

One thing that was different is that it provided guidance on exactly where to position the phone (“place the top of your phone over the centre of your passport”).  

I went back to the Anyline iOS app and tried again - and it worked.  Obvious the nfc read is VERY sensitive to the position of the phone - and since your app provides no guidance on that, I guess most people will place the phone crates over the centre of the passport (ie just flat on top of each other with edges aligned).  But if you do that, the nfc read will fail - so I think all you need it to improve user guidance on positioning

**Comment by rodrigowpl** [comment] 2020-06-04 21:44
Also tried here using ReadID app and it worked perfectly and fast, in the first try.

Tried again using Anyline app it continues not working no matter how I try position my passport

**Comment by onthebreeze** [comment] 2020-06-04 21:48
Are there protocol differences between passports ?  Even if so, a commercial app should support them all - especially for nations like Brazil - it’s not exactly a small country - over 200 million people

**Comment by ricardocolombo** [comment] 2020-06-05 08:50
Hello @rodrigowpl and @onthebreeze!
My name is Ricardo, I am Brazilian and also work here at Anyline :)
I'm not an expert in RN, but I've developed the NFC functionality for Xamarin.iOS and now I'm looking into this issue with philipp and amir.

Regarding the protocol differences, that is not going to be a problem. I myself tested a few Brazilian passports (mine, my wife's, my father-in-law's) with success.

@rodrigowpl, using the Anyline OCR app (from Apple Store - version 21), does it break even if you follow the procedures that @onthebreeze mentioned? 

> "place the top of your phone over the centre of your passport"

Does it display the same error message? 

> "Sorry, there was a problem reading the passport. Please try again"

Also, if it does, does it show any other messages before, or the popup instantly shows this message?

Thanks!
Ricardo

**Comment by ricardocolombo** [comment] 2020-06-05 15:58
Just to be 100% sure, I have configured a brand new machine from the beginning, until our ReactNative examples app.
In this video, you can see that the scanning of Brazilian passports is not a limitation.

![NFC_BrazilianPassport](https://user-images.githubusercontent.com/54582962/83897420-dffa4100-a755-11ea-8928-b9931fbacb31.gif)

I will write another comment with a few more instructions, just to make sure that no step is missing :)

**Comment by ricardocolombo** [comment] 2020-06-05 16:22
These are the basic step-by-step to make NFC work on our RN Examples App:

NFC Reader can only be used to scan passports on the **iPhones** from model **7** and **up**, running **iOS 13** and **up**. 
To use the NFC reader, Apple requires that the project is signed with a Provisioning Profile with **NFC capability** (note that Wildcard Provisioning Profiles cannot be used when signing projects with NFC capability). To create the required files, access the [Apple developer portal](https://developer.apple.com/account/resources/certificates/list) and do the following:

**1.** Create your Development/Distribution Certificate
**2.**  Download the certificate and install it on your Mac
**3.**  Create an App Identifier for your specific Bundle ID, with NFC Tag Reading capability

![1_appId](https://user-images.githubusercontent.com/54582962/83898735-990d4b00-a757-11ea-9c97-9523bb751249.png)
![2_appId](https://user-images.githubusercontent.com/54582962/83898754-9f9bc280-a757-11ea-8887-e2ae00aea7f0.png)

**4.** Create a Provisioning Profile linked with your previously created Certificate and App Identifier

![image](https://user-images.githubusercontent.com/54582962/83898825-bcd09100-a757-11ea-8495-98dce652676a.png)

**5.** Download the Provisioning Profile and install it on your Mac

**6.** Open Xcode and, in Signing & Capabilities do the following:
    a) Put in the same Bundle Identifier that you used to create the app (Step 3) on the Apple Developer Portal
    b) Select the previously created Provisioning Profile (Step 4)
    c) Click the “+ Capability” button and add the “Near Field Communication Tag Reading” capability

![4_signingcapability](https://user-images.githubusercontent.com/54582962/83899031-0e791b80-a758-11ea-874e-5b6e3b44873c.png)

**7.** In the info.plist file, make sure that you have:
   a) KEY: “NFCReaderUsageDescription” 
       VALUE: <string>Please allow NFC access to read passports</string>
   b) KEY: “com.apple.developer.nfc.readersession.iso7816.select-identifiers” 
       VALUE: <array> <string>A0000002471001</string> </array>
   c) KEY: “com.apple.developer.nfc.readersession.formats” 
       VALUE: <array> <string>NDEF</string><string>TAG</string> </array>

![5_infoplist](https://user-images.githubusercontent.com/54582962/83899176-43856e00-a758-11ea-8d00-04c77aa8fceb.png)

**8.**  Now, on the project structure (Finder), edit the file:
example > RNExampleApp > config > **NFCAndMRZConfig.js**
On this file, change the "**license**" value to the specific _Anyline License_ linked to you Bundle Identifier (used on Step 3).
**9.** Run the app and go to ID > NFC+MRZ Scanner

Please let us know if these steps help you or if you require any further assistance!  

Best regards,
Ricardo

**Comment by onthebreeze** [comment] 2020-06-05 23:17
Thanks Ricardo - hopefully we will get it working soon

**Comment by onthebreeze** [comment] 2020-06-07 23:10
yes ok.  I just tested my UK passport again with ReadID iOS app and Anyline iOS app.  both work fine and both have exactly the same sensitivity to positioning of phone over the passport.  Neither work when phone is overlayed on passport, but as I drag the phone down the passport, they both start to work at exactly the same position.

Then I tried with my AU passport.  In that case REadID worked first time but Anyline gave "stack error, please try again" the first time - but from then on it worked ok and I cannot get it to fail again.  Not sure what triggered that initial read error with the anyline app.

Please note that both these tests are done with the app, not with the SDK/react library.

**Comment by rodrigowpl** [comment] 2020-06-08 18:22
@ricardocolombo thanks for your help and attention.

I've followed all those steps like we have been repeatedly discussing in this issue, if not, the scan wouldn't even working or open, right ?!
I have 100% of sure that everything is right on my side, but even so, my passport is not working! And to make sure I've also tested using your official App [Anyline OCR Scanner](https://apps.apple.com/at/app/anyline-ocr-scanner/id1121273374), the same thing. I've tried **four** different passports, my, my wife, my friend and my friend's wife and nothing.
So please there's definitely something happening here.

![image](https://user-images.githubusercontent.com/18172307/84065705-2b516100-a99b-11ea-995f-05345387b852.png)

Could we please schedule a call so that I can show you exactly what I'm doing? 
my email: rodrigo@divisio.com.br.
Sorry about to say but in this issue, you guys just keep saying to follow steps and steps, repeatedly and there's nothing new since the begging.

Ps: with ReadID app works perfectly since the first try here.

Regards,

**Comment by ricardocolombo** [comment] 2020-06-09 10:12
Hi @rodrigowpl! 

Thank you for the information provided. It seems that our SDK might have some restrictions regarding the combination (phone + passport) being used to scan.

This Thursday is a holiday in Austria, but we can set up a quick call for tomorrow (Wednesday, 10), around 14:30h (CEST - UTC +2) - 9:30h Brasília Time. Would this work for you?
If this is okay, we can send an invite to your e-mail.

To prepare for the call, are you able to test the NFC Scanner also in another iPhone (from model 7 and up), different than the iPhone XR? Can you also test your passport with our [Android App](https://play.google.com/store/apps/details?id=io.anyline.examples.store)?


Best regards,

**Comment by rodrigowpl** [comment] 2020-06-09 12:15
@ricardocolombo  That works, for me.
Btw I'm available today during the day BRT time, please feel free to send me an invite: rodrigo@divisio.com.br

**Comment by ricardocolombo** [comment] 2020-06-09 12:42
@rodrigowpl Great! I sent an invite to you and to @AngelaBrett-Anyline. She is one of our iOS developers and will be able to help us investigate better what could be happening on the SDK size.

Best regards,

**Comment by rodrigowpl** [comment] 2020-06-09 12:48
That's awesome, just accepted

**Comment by rodrigowpl** [comment] 2020-06-10 23:43
@ricardocolombo just an update, I've tried running your native ios example, but without success, unfortunately, I'm not IOS/Xcode expert, is there another way that I could help you to debug it?

but btw just a guess:
As you said, if you are using MRZ data to authenticate, like here
https://github.com/Anyline/anyline-ocr-examples-ios/blob/master/AnylineExamples/Anyline%20Examples%20Source/NFC/ViewController/ALNFCScanViewController.m#L171

That's the more explainable reason the would cause the issue, we just would need to debug this code, but I would need help on that

**Comment by rodrigowpl** [comment] 2020-06-11 00:04
I would suggest putting more logs in that part so the non-ios developers could help seeing what's happening, is that possible?

**Comment by AngelaBrett-Anyline** [comment] 2020-06-16 09:01
Are you able to run the native iOS app from Xcode at all? If so, please add the following line:

`    NSLog(@"NFC failed with error: %@",error.localizedDescription);
`

after the line:

`- (void)nfcFailedWithError:(NSError * _Nonnull)error {
`

and then run the Passport NFC scanner and see if you get that message in the Xcode console (you might need to go to View→Debug Area→Show Debug Area to be able to see the logs) and let us know what it says. If you think that the problem could be with the MRZ data used to authenticate, you could also add this line:

`    NSLog(@"passport number: %@\ndate of birth: %@\n date of expiry: %@",self.passportNumberForNFC, self.dateOfBirth, self.dateOfExpiry);
`

After this line:

`- (void)readNFCChip {
`

but for privacy reasons please **do not post the results of that here**. Note that the dates will not be logged in the exact format that they will be sent to the NFC chip, but it might be useful to see the passport number being used, as in some cases the passport number used for NFC should have ‘<‘ at the end.

If you are not able to run the app, what happens when you try? Perhaps I can help.

**Comment by berndkamplanyline** [comment] 2022-02-18 10:53
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!

**Closed by berndkamplanyline** 2022-02-18 10:53 UTC
